language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-anyandgo' ]; then cd .. && eval "mv $currentfolder generator-anyandgo" && cd generator-anyandgo; fi

